### PR TITLE
Add ignored test case for conflicting deps in unrelated ws members

### PR DESCRIPTION
**Pull request by maciektr**
**Stack**:
- #1007 ⬅
- #1030

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

### CODE REVIEW

**Comment by szymmis** [comment]
What are those tests related to, especially in the context that they are ignored?

**Comment by maciektr** [comment]
@szymmis basically bugs that we should sort out eventually

**Review by mkaput — COMMENTED** [review]
I do understand the reasoning. I am afraid how this will play out with PubGrub, as I believe the canonical algorithm will attempt to unify `some_dep` in this scenario.

Did some user request this behaviour? Do we need to commit to it?

**Comment by maciektr** [comment]
> Did some user request this behaviour? Do we need to commit to it?

Nope, just a thought experiment

**Comment by mkaput** [comment]
> Though it seems that having same dep with different versions may actually make sense even in cairo - when the graph is disconnected.

That's a highly philosophical argument. One could want instead to use a single version of `dep` throughout the workspace because it's well -- a workspace. Given a workspace of multiple contracts, I'm not sure the author will want the contract A to have dependency v0, while contract B -- v1.

I think we have to ask users on Telegram.

**Pull request closed without merging**
